# Generated by Django 3.2.4 on 2021-06-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribute',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
