# Generated by Django 3.2.4 on 2021-06-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210630_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribute',
            name='file',
        ),
        migrations.AlterField(
            model_name='contribute',
            name='email',
            field=models.EmailField(max_length=1000),
        ),
    ]
